# Generated by Django 3.1.1 on 2020-09-05 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('testTopic', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('testCode', models.SlugField(blank=True, null=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classTest', to='classroom.classroom')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='MCQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option_a', models.TextField()),
                ('option_b', models.TextField()),
                ('option_c', models.TextField()),
                ('option_d', models.TextField()),
                ('answer', models.CharField(choices=[('a', models.TextField()), ('b', models.TextField()), ('c', models.TextField()), ('d', models.TextField())], max_length=1)),
                ('questionCode', models.SlugField(blank=True, null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testquestion', to='classroom.classtest')),
            ],
        ),
    ]
