# Generated by Django 3.1.1 on 2020-09-05 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classroom', '0003_classtest_mcquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTestResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isattempted', models.BooleanField(default=False)),
                ('student_score', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_Response', to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_no', to='classroom.classtest')),
            ],
            options={
                'unique_together': {('student', 'test')},
            },
        ),
        migrations.CreateModel(
            name='MCQStudentResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_selected', models.CharField(default='u', max_length=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_for_response', to='classroom.mcquestion')),
                ('student_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_student_status', to='classroom.studenttestresponse')),
            ],
            options={
                'unique_together': {('student_response', 'question')},
            },
        ),
    ]
