# Generated by Django 3.1.1 on 2020-09-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_mcqstudentresponse_studenttestresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcquestion',
            name='answer',
            field=models.CharField(choices=[('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd')], max_length=1),
        ),
    ]
